### ISSUE TITLE
Bug: Media Items don't show up in single view

### ISSUE THREAD

**Issue by mheiniger** [Joomla-Bible-Study/Proclaim#834] opened 2021-03-17 22:51 UTC
After the last update to Proclaim 9.2.5 in single view (`$type === 'sermon'`) the media playback part was missing. In the list view  (`$type === 'sermons'`) they were still visible.

After some digging found that here:
https://github.com/Joomla-Bible-Study/Proclaim/blob/cc22399a7f6a9cc32bd8744b0d2d0a4453a84348/site/lib/listing.php#L480

`$mediafile->study_id` is a `string`
and 
`$item->id` is an `int`
so after the code has changed from `==` to `===` that statement will never become true.

Interestingly for in the list view both fields are type `String`

**Comment by bcordis** [comment] 2021-04-06 14:38
Thank you for your impute we see this and have a new release to fix this now. Duplicate of #837

**Comment by bcordis** [comment] 2021-04-06 21:56
Released with 9.2.5

**Closed by bcordis** 2021-04-06 21:56 UTC
Labels: Accepted, Bug-Blocker
